# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160921_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='f01',
            field=models.CharField(default='.', max_length=99, verbose_name='編號'),
        ),
        migrations.AddField(
            model_name='document',
            name='f02',
            field=models.CharField(default='.', max_length=99, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='document',
            name='f03',
            field=models.CharField(default='.', max_length=99, verbose_name='應徵職務'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='%Y-%m', verbose_name='簡歷檔案'),
        ),
    ]
