# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160921_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='f04',
            field=models.CharField(default='.', max_length=99, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='document',
            name='f05',
            field=models.CharField(choices=[('安排面試', '安排面試'), ('面試不通過', '面試不通過'), ('面試通過', '面試通過')], default='.', max_length=99, verbose_name='面試記錄'),
        ),
    ]
